# Document:
# http://simiki.org/docs/configuration.html

url:
title: zwt的个人wiki
keywords: Memory.
description: Wiki.
author: zwt

root: /wiki

deploy:
  - type: git
    remote: origin
    branch: gh-pages

theme: simple